name: CICD

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'

      - name: print
        run: echo "GITHUB_REF_NAME=${GITHUB_REF_NAME} GITHUB_REF_SLUG=${GITHUB_REF_SLUG}"
      - name: CI
        run: env TAG=${GITHUB_REF_NAME}  make ci

      - name: Deploy to Docker registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kevholditch/pagerduty-slack-sync
          tag_with_ref: true


