name: CICD

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'

      - name: CI
        run: make ci

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF} | cut -d '/' -f3)

      - name: Build the tagged Docker image
        run: docker build . --file ./build/package/Dockerfile --tag kevholditch/pagerduty-slack-sync:${{steps.vars.outputs.tag}}

      - name: Push the tagged Docker image
        run: docker push  kevholditch/pagerduty-slack-sync:${{steps.vars.outputs.tag}}


