name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'

      - name: Install dependencies
        run: |
          go get -u golang.org/x/lint/golint

      - name: Run build
        run: env GOMODULE111=on go build ./cmd/pagerduty-slack-sync

      - name: Run vet & lint
        run: |
          go vet -v ./...
          golint -v ./...

      - name: Test
        run: go test -v ./...


#  # The "deploy" workflow
#  deploy:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#    needs: [build] # Only run this workflow when "build" workflow succeeds
#    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
#    steps:
#      - uses: actions/checkout@v2
#
#      # Deploy to Docker registry
#      - name: Deploy to Docker registry
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          repository: wilsontanwm/gosimple
#          tag_with_ref: true