name: CICD

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'

      - name: CI
        run: make ci

      - name: Deploy to Docker registry
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: kevholditch/pagerduty-slack-sync
            tag_with_ref: true


